kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
data:
  # this will need to be templatized
  config: |-
    logger:
      level: 4 
