apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flinkk8soperator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.flinkk8soperator.app }}
spec:
  replicas: {{ .Values.flinkk8soperator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.flinkk8soperator.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.flinkk8soperator.app }}
        app.kubernetes.io/version: 0.5.0
    spec:
      serviceAccountName: {{ .Values.flinkk8soperator.serviceAccountName }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.flinkk8soperator.configMap.name }}
          items:
          - key: config
            path: {{ .Values.flinkk8soperator.configMap.items.path }}
      containers:
      - name: {{ .Values.flinkk8soperator.containers.name }}
        image: {{ .Values.flinkk8soperator.containers.image }}
        command:
        - flinkoperator
        args:
        - --logtostderr
        - --config
        - /tmp/flinkoperator/config*/config.yaml
        env:
        - name: OPERATOR_NAME
          value: {{ .Values.flinkk8soperator.containers.env.value }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.flinkk8soperator.containers.ports.containerPort }}
        resources:
          requests:
            memory: {{ .Values.flinkk8soperator.containers.resources.requests.memory }}
            cpu: {{ .Values.flinkk8soperator.containers.resources.requests.cpu }}
          limits:
            memory: {{ .Values.flinkk8soperator.containers.resources.limits.memory }}
            cpu: {{ .Values.flinkk8soperator.containers.resources.limits.cpu }}
        volumeMounts:
        - name: {{ .Values.flinkk8soperator.containers.volumeMounts.name }}
          mountPath: {{ .Values.flinkk8soperator.containers.volumeMounts.mountPath }}
