namespace: 
  name: flink-operator
  enabled: false

configmap:
  name: flink-operator-config
  
flinkk8soperator:
  name: flinkoperator
  app: flinkoperator
  replicas: 1
  serviceAccountName: flinkoperator
  volumeName: config-volume
  configMap:
    name: flink-operator-config
    items:
      path: config.yaml
  containers:
    name: flinkoperator-gojson
    image: docker.io/lyft/flinkk8soperator:v0.5.0
    env:
      value: flinkk8soperator
    imagePullPolicy: IfNotPresent
    ports: 
        containerPort: 10254
    resources:
      requests:
        memory: "4Gi"
        cpu: "4"
      limits:
        memory: "8G"
        cpu: "8"
    volumeMounts:
      name: config-volume
      mountPath: /tmp/flinkoperator/config



# flinkk8soperator_local: 
#   name: flinkk8soperator
#   namespace: {{ .Release.Namespace }}
#   app: flinkk8soperator
#   volumeName: config-volume
#   replicas: 1
#   configMapKey: development
#   configMapPath: flinkk8soperator_config.yaml
#   containers:
#   - name: flinkk8soperator
#     image: flinkk8soperator
#     env:
#     - name: OPERATOR_NAME
#       value: flinkk8soperator
#     imagePullPolicy: Never
#     ports: 
#       - containerPort: 10254
#     resources:
#       requests:
#         memory: "1Gi"
#         cpu: "1"
#       limits:
#         memory: "8G"
#         cpu: "8"
#     volumeMounts:
#     - name: config-volume
#       mountPath: /etc/flinkoperator/config


rolebinding:
  name: flinkoperator
  apiVersion: rbac.authorization.k8s.io/v1beta1
  apiGroup: rbac.authorization.k8s.io