{{- if .Values.keycloak_db.ssl_cert.enabled }}
apiVersion: {{ .Values.keycloak_db.ssl_cert.apiVersion }}
kind: Secret
metadata:
  name: {{ .Values.keycloak_db.ssl_cert.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root.crt: {{ .Values.keycloak_db.ssl_cert.rootCrt | b64enc }}
{{- end }}