{{- if .Values.custom_resource.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ "credential" }}-{{ .Values.custom_resource.name }}
    namespace: {{ .Release.Namespace }}
data:
    ADMIN_PASSWORD: {{ .Values.custom_resource.credentials.ADMIN_PASSWORD | b64enc }}
    ADMIN_USERNAME: {{ .Values.custom_resource.credentials.ADMIN_USERNAME | b64enc }}
type: Opaque
{{- end }}