{{- if .Values.operator.enabled }}
apiVersion: {{ .Values.operator.apiVersion }}
kind: Deployment
metadata:
  name:  {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      containers:
        - name: {{ .Values.operator.name }}
          # Replace this with the built image name
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
          command:
          -  {{ .Values.operator.command }}
          imagePullPolicy: {{ .Values.operator.image.PullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.operator.Env.OPERATOR_NAME }}
{{ end }}