{{- if .Values.role_binding.enabled }}
kind: RoleBinding
apiVersion: {{ .Values.keycloak_roles.apiVersion }}
metadata:
  name: {{ .Values.role_binding.name }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.role_binding.Subjects.name }}
roleRef:
  kind: Role
  name: {{ .Values.role_binding.roleRef.name }}
  apiGroup: {{ .Values.keycloak_roles.apiGroup }}
{{ end }}