{{- if .Values.service_account.enabled }}
apiVersion: {{ .Values.service_account.apiVersion }}
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}