apiVersion: crossplane.industry-fusion.com/v1alpha1
kind: DigitalTwinPlatform
metadata:
  name: ionos-example
spec:
  parameters:
    services:
      kafka:
        version: 0.29.0
      postgres:
        version: 1.7.1
      minio:
        version: 4.5.2
  compositionSelector:
    matchLabels:
      provider: ionos
  writeConnectionSecretToRef:
    name: digitaltwinplatform-ionos-example-kubeconfig


