apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdigitaltwinplatforms.crossplane.industry-fusion.com
spec:
  group: crossplane.industry-fusion.com
  names:
    kind: XDigitalTwinPlatform
    plural: xdigitaltwinplatforms
    singular: xdigitaltwinplatform
  claimNames:
    kind: DigitalTwinPlatform
    plural: digitaltwinplatforms
    singular: digitaltwinplatform
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: A XDigitalTwinPlatform is a composite resource.
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    services:
                      type: object
                      properties:
                        kafka:
                          type: object
                          properties:
                            version:
                              type: string
                        postgres:
                          type: object
                          properties:
                            version:
                              type: string
                        minio:
                          type: object
                          properties:
                            version:
                              type: string
                        nginx:
                          type: object
                          properties:
                            version:
                              type: string
                        certmanager:
                          type: object
                          properties:
                            version:
                              type: string
                      required:
                        - kafka
                        - postgres
                        - minio
                        - nginx
                        - certmanager
                  required:
                    - services
              required:
                - parameters
